### PR TITLE
Serial refactor

### LINKED ISSUE #51: Lost serial data using a BBC micro:bit
Data is lost when using a Python REPL on a BBC micro:bit. May be related to #50 ?

To reproduce
- Download and flash an empty script (defaults to REPL) from https://python.microbit.org/
- Run serial example (usb/hid/webusb) from repo `examples/daplink-serial`
- Check output of `help()` command

I get:
```
Select a device to listen to serial output:
1: "BBC micro:bit CMSIS-DAP"
Listening at 115200 baud...
he
l
p
(
)
Type 'dir()' to see what stuff is available. For goodness sake
 type 'import this'.

Control commands:
  CTRL-C        -- 
stop a running program
  CTRL-D        -- on a blank line, do
 a soft reset of the micro:bit
  CTRL-E        -- enter paste
 mode, turning off auto-indent

For a list of available modu
les, type help('modules')

For more information about Python
, visit: http://python.org/
To find out about MicroPython, vi
sit: http://micropython.org/
Python/micro:bit documentation i
s here: https://microbit-micropython.readthedocs.io/
>>> 
```

Building micropython with a default baud rate of 9600 appears to output the correct data, but it would be great to get this working at the current default of 115200.

However even at 9600 baud DAPjs throws `Bad response` errors. I'm not certain if data is lost every time this occurs. 

```
dap.bundle.js:1014 Uncaught (in promise) Error: Bad response for 131 -> 132
    at dap.bundle.js:1014
(anonymous) @ dap.bundle.js:1014
Promise.then (async)
(anonymous) @ dap.bundle.js:543
setInterval (async)
DAPLink.startSerialRead @ dap.bundle.js:541
(anonymous) @ python-main.js:932
Promise.then (async)
(anonymous) @ python-main.js:931
Promise.then (async)
doSerial @ python-main.js:910
(anonymous) @ python-main.js:1039
dispatch @ jquery-2.1.4.min.js:3
r.handle @ jquery-2.1.4.min.js:3
dap.bundle.js:1014 Uncaught (in promise) Error: Bad response for 132 -> 131
    at dap.bundle.js:1014
(anonymous) @ dap.bundle.js:1014
Promise.then (async)
DAPLink.serialWrite @ dap.bundle.js:578
io.onVTKeystroke @ python-main.js:965
hterm.Terminal.onVTKeystroke @ hterm_all.js:15259
hterm.Keyboard.onKeyPress_ @ hterm_all.js:6259
```

Please let me know if there's any more info I can gather to help

### LINKED ISSUE #60: EVENT_SERIAL_DATA emits a string, could we get the raw data?
Listening to the EVENT_SERIAL_DATA gets the DATA as a string format.

https://github.com/ARMmbed/dapjs/blob/87f20dcddf9dd026703daed000ae77d3c1764df4/src/daplink/index.ts#L161-L168

Any chance we can get the raw data?
As MicroPython strings are UTF-8 when the data is converted into a JS string (UTF-16) we get some characters decoded incorrectly, like `£` as `Â£`.

### PR DESCRIPTION
**Pull request by thegecko**
This PR updates the serial output code, specifically:

- Exposes the raw SerialRead function
- Uses `setTimeout` instead of `setInterval` while polling serial output to eradicate any overlap
- Reduced default serial poll to 100 ms
- Text decode updated to support double-byte characters
- Confirmed to support strings of more than 64 chars
- Added guard against incorrect VENDOR_CODE_COMMAND result being output
- Added connection status to target and guards against re-connect/re-disconnect
- Only polls serial output when there is a relevant event listener present
- Added auto-connect functionality to only open target connection during each read

Resolves #60 and may fix #51 

cc @microbit-sam, @jaustin, @microbit-carlos

### CODE REVIEW

**Comment by thegecko** [comment]
@arekzaluski Ready for re-testing

File: src/daplink/index.ts [hunk 1]
```diff
@@ -31,16 +33,21 @@ const DEFAULT_BAUDRATE = 9600;
 /**
  * @hidden
  */
-const DEFAULT_SERIAL_DELAY = 200;
+const DEFAULT_SERIAL_DELAY = 100;
```
Comment (arekzaluski) [inline src/daplink/index.ts]: 👍

File: src/daplink/index.ts [hunk 2]
```diff
@@ -146,51 +191,87 @@ export class DAPLink extends CmsisDAP implements Proxy {
...
-                    if (dataLength !== 0) {
-                        const offset = 2;
-                        const dataArray = serialData.buffer.slice(offset, offset + dataLength);
-                        const numberArray = Array.prototype.slice.call(new Uint8Array(dataArray));
-                        const data = String.fromCharCode.apply(null, numberArray);
-                        this.emit(DAPLink.EVENT_SERIAL_DATA, data);
-                    }
-                }
-            });
-        }, serialDelay);
```
Comment (arekzaluski) [inline src/daplink/index.ts]: 👍

File: src/daplink/index.ts [hunk 3]
```diff
@@ -146,51 +191,87 @@ export class DAPLink extends CmsisDAP implements Proxy {
...
+            // First byte contains the vendor code
+            if (serialData.getUint8(0) !== DAPLinkSerial.READ) {
+                return undefined;
+            }
+
+            // Second byte contains the actual length of data read from the device
+            const dataLength = serialData.getUint8(1);
+            if (dataLength === 0) {
+                return undefined;
+            }
```
Comment (arekzaluski) [inline src/daplink/index.ts]: Much easier to read.

File: src/daplink/index.ts [hunk 4]
```diff
@@ -146,51 +191,87 @@ export class DAPLink extends CmsisDAP implements Proxy {
...
+     * @param serialDelay The serial delay to use (default 100)
+     * @param autoConnect whether to automatically connect to the target (default true)
+     */
+    public async startSerialRead(serialDelay: number = DEFAULT_SERIAL_DELAY, autoConnect = true) {
+        this.serialPolling = true;
+
+        while (this.serialPolling) {
+
+            // Don't read serial output unless we have event listeners
+            if (this.serialListeners) {
```
Comment (arekzaluski) [inline src/daplink/index.ts]: 👍

File: src/daplink/index.ts [hunk 5]
```diff
@@ -146,51 +191,87 @@ export class DAPLink extends CmsisDAP implements Proxy {
...
+            return serialData.buffer.slice(offset, offset + dataLength);
+        });
+    }
+
+    /**
+     * Start listening for serial data
+     * @param serialDelay The serial delay to use (default 100)
+     * @param autoConnect whether to automatically connect to the target (default true)
+     */
+    public async startSerialRead(serialDelay: number = DEFAULT_SERIAL_DELAY, autoConnect = true) {
```
Comment (arekzaluski) [inline src/daplink/index.ts]: I like autoConnect idea.

File: src/daplink/index.ts [hunk 6]
```diff
@@ -146,51 +191,87 @@ export class DAPLink extends CmsisDAP implements Proxy {
...
+
+                // Put state back
+                if (connectedState === false && autoConnect === true) {
+                    await this.disconnect();
+                }
+
+                if (serialData !== undefined) {
+                    const data = decoder.decode(serialData);
+                    this.emit(DAPLink.EVENT_SERIAL_DATA, data);
+                }
```
Comment (arekzaluski) [inline src/daplink/index.ts]: This code will now every 100 ms(default value) send additional 4 DAP commands (1 for disconnect and 3 for connect) when `autoConnect` is set to true and `connect()` was not called before. Has it been done like it on purpose? I understand that you want to keep the connection status as it was before and only open it for a read?

Comment (thegecko) [reply src/daplink/index.ts]: Yes,  you can choose to explicitly connect and disconnect as before,  but it's bad practice to keep a channel continually open.  The default now connects and disconnects on demand
